#
# Wizard autogenerated makefile.
# DO NOT EDIT, use the mobilinkd-tnc1_user.mk file instead.
#

# Constants automatically defined by the selected modules


# Our target application
TRG += mobilinkd-tnc1

mobilinkd-tnc1_PREFIX = "/usr/bin/avr-"

mobilinkd-tnc1_SUFFIX = ""

mobilinkd-tnc1_SRC_PATH = mobilinkd-tnc1

mobilinkd-tnc1_HW_PATH = mobilinkd-tnc1

# Files automatically generated by the wizard. DO NOT EDIT, USE mobilinkd-tnc1_USER_CSRC INSTEAD!
mobilinkd-tnc1_WIZARD_CSRC = \
	bertos/algo/crc_ccitt.c \
	bertos/cpu/avr/drv/ser_avr.c \
	bertos/cpu/avr/drv/ser_mega.c \
	bertos/cpu/avr/drv/timer_avr.c \
	bertos/cpu/avr/drv/timer_mega.c \
	bertos/drv/ser.c \
	bertos/drv/timer.c \
	bertos/io/kfile.c \
	bertos/mware/event.c \
	bertos/mware/formatwr.c \
	bertos/mware/hex.c \
	bertos/net/afsk.c \
	bertos/net/hdlc.c \
	bertos/net/kiss.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE mobilinkd-tnc1_USER_PCSRC INSTEAD!
mobilinkd-tnc1_WIZARD_PCSRC = \
	bertos/mware/formatwr.c \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE mobilinkd-tnc1_USER_CPPASRC INSTEAD!
mobilinkd-tnc1_WIZARD_CPPASRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE mobilinkd-tnc1_USER_CXXSRC INSTEAD!
mobilinkd-tnc1_WIZARD_CXXSRC = \
	 \
	#

# Files automatically generated by the wizard. DO NOT EDIT, USE mobilinkd-tnc1_USER_ASRC INSTEAD!
mobilinkd-tnc1_WIZARD_ASRC = \
	 \
	#

mobilinkd-tnc1_CPPFLAGS = -D'CPU_FREQ=(16000000UL)' -D'ARCH=(ARCH_DEFAULT)' -D'WIZ_AUTOGEN' -I$(mobilinkd-tnc1_HW_PATH) -I$(mobilinkd-tnc1_SRC_PATH) $(mobilinkd-tnc1_CPU_CPPFLAGS) $(mobilinkd-tnc1_USER_CPPFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
mobilinkd-tnc1_LDFLAGS = $(mobilinkd-tnc1_CPU_LDFLAGS) $(mobilinkd-tnc1_WIZARD_LDFLAGS) $(mobilinkd-tnc1_USER_LDFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
mobilinkd-tnc1_CPPAFLAGS = $(mobilinkd-tnc1_CPU_CPPAFLAGS) $(mobilinkd-tnc1_WIZARD_CPPAFLAGS) $(mobilinkd-tnc1_USER_CPPAFLAGS)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
mobilinkd-tnc1_CSRC = $(mobilinkd-tnc1_CPU_CSRC) $(mobilinkd-tnc1_WIZARD_CSRC) $(mobilinkd-tnc1_USER_CSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
mobilinkd-tnc1_PCSRC = $(mobilinkd-tnc1_CPU_PCSRC) $(mobilinkd-tnc1_WIZARD_PCSRC) $(mobilinkd-tnc1_USER_PCSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
mobilinkd-tnc1_CPPASRC = $(mobilinkd-tnc1_CPU_CPPASRC) $(mobilinkd-tnc1_WIZARD_CPPASRC) $(mobilinkd-tnc1_USER_CPPASRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
mobilinkd-tnc1_CXXSRC = $(mobilinkd-tnc1_CPU_CXXSRC) $(mobilinkd-tnc1_WIZARD_CXXSRC) $(mobilinkd-tnc1_USER_CXXSRC)

# Automatically generated by the wizard. PLEASE DO NOT EDIT!
mobilinkd-tnc1_ASRC = $(mobilinkd-tnc1_CPU_ASRC) $(mobilinkd-tnc1_WIZARD_ASRC) $(mobilinkd-tnc1_USER_ASRC)

# CPU specific flags and options, defined in the CPU definition files.
# Automatically generated by the wizard. PLEASE DO NOT EDIT!
mobilinkd-tnc1_MCU = atmega328p
mobilinkd-tnc1_CPU_CPPFLAGS = -Os -Ibertos/cpu/avr/
mobilinkd-tnc1_PROGRAMMER_CPU = atmega328p
mobilinkd-tnc1_STOPFLASH_SCRIPT = bertos/prg_scripts/avr/stopflash.sh
mobilinkd-tnc1_STOPDEBUG_SCRIPT = bertos/prg_scripts/none.sh
mobilinkd-tnc1_DEBUG_SCRIPT = bertos/prg_scripts/nodebug.sh
mobilinkd-tnc1_FLASH_SCRIPT = bertos/prg_scripts/avr/flash.sh

include $(mobilinkd-tnc1_SRC_PATH)/mobilinkd-tnc1_user.mk
